services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: locus
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d locus"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=locus
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./Front
      dockerfile: Dockerfile
    ports:
      - "3501:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_YANDEX_MAPS_API_KEY=${VITE_YANDEX_MAPS_API_KEY}
    depends_on:
      - backend
    volumes:
      - ./Front:/app:delegated
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  postgres_data:
